### ISSUE TITLE
does it support rational_polynomial calibration from camera_info or config file?

### ISSUE THREAD

**Issue by FPSychotic** [NVIDIA-ISAAC-ROS/isaac_ros_visual_odometry#10]
i,m no able to make work a stereo camera, I think it is due to its rational_polynomial calibration , can be supported in a easy way? as config file?

**Comment by hemalshahNV** [comment]
We do not yet support rational polynomial distortion model in Elbrus visual odometry. You can work around this by rectifying the image using isaac_ros_image_proc first and then passing in the undistorted image with pinhole model into Elbrus. Adding rational polynomial distortion model support is being prioritized for a future release.

**Comment by FPSychotic** [comment]
Thanks, that workaround sounds nice to learn a little about, as I have no
experience with calibrations and so on. So time to learn a little.

Thanks!

**Comment by FPSychotic** [comment]
Thanks a lot , I will try that workaround.
Thanks!

**Comment by martinlucan** [comment]
@hemalshahNV Hi, has rational_polynomial calibration model been already released? Thank you.
